[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_ENVIRONMENT = "production"

# Production environment variables will be set in Netlify dashboard
# VITE_SUPABASE_URL = "your-production-supabase-url"
# VITE_SUPABASE_ANON_KEY = "your-production-supabase-anon-key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200